### PR TITLE
Updating to solr 7.6.0 and updating other libs

### PR DESCRIPTION
**Pull request by AceHack**
Updating to solr 7.6.0 based on https://github.com/inoio/solrs/issues/62

### CODE REVIEW

**Comment by magro** [comment]
Thanks for the PR, will do a release soon.

**Comment by AceHack** [comment]
Thank you so much, I really appreciate everything.

**Comment by magro** [comment]
Thanks as well :-)

solrs 2.3.0 is on its way to maven central.

**Comment by AceHack** [comment]
I've never published to maven central before, how long does it usually take to show up?  Thanks.

**Comment by magro** [comment]
@AceHack It usually takes an hour or less. At http://central.maven.org/maven2/io/ino/solrs_2.12/2.3.0/ timestamps are "2019-06-12 19:28" (not sure about the timezone).

**Pull request merged**
