### PR TITLE
Make RoundRobinLB thread safe

### PR DESCRIPTION
**Pull request by billyean**
Current RoundRobinLB is not thread-safe, it could cause unbalanced requests hit on solr cloud in the highly-concurrent environment.  Fixed it with AtomicInteger with overflow checking

### CODE REVIEW

**Comment by magro** [comment]
Thanks for the PR, LGTM!

Let's fix the travis issue first before merging. If you can have a look at it that would be awesome, otherwise I'll try to find time for that soon.

**Comment by magro** [comment]
This might help - could you try that?

https://travis-ci.community/t/solved-oraclejdk8-installation-failing-still-again/3428

**Comment by magro** [comment]
I just fixed the travis build with #70 - can you please rebase your change on top of master?

**Comment by billyean** [comment]
Done, I also fixed the index start with 1 since old index start from 1

**Pull request merged**
