### PR TITLE
Support Alias

### PR DESCRIPTION
**Pull request by insford**
add support for alias

### CODE REVIEW

**Comment by magro** [comment]
Thanks for the PR! Can you please add a test for this?

**Comment by insford** [comment]
yes! I'll try to add a test case.

**Comment by magro** [comment]
@insford are you still on it?

**Comment by insford** [comment]
@magro
I was super busy releasing a new project at my work.
I'm on my vacation now, so when i get back home, I'll work on it.

**Comment by magro** [comment]
@insford no hurry, enjoy your vacation!

**Pull request closed without merging**
